easy_admin:
    entities:
        Categorie:
            class: App\Entity\Categorie
            form:
                fields:
                    - {property: 'name'}
                    - {property: 'slug'}